import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import './globals.css'
import AppHeaders from '@/components/AppHeaders'
import { ThemeProvider } from '@/hooks/ThemeContext';
import { Themes } from '@/constants/themes'

// import '@fontsource/roboto/300.css';
// import '@fontsource/roboto/400.css';
// import '@fontsource/roboto/500.css';
// import '@fontsource/roboto/700.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const theme = cookieStore.get('theme')?.value || Themes.TWILIGHT;

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider serverTheme={theme}>
            <AppHeaders>
              {children}
            </AppHeaders>
        </ThemeProvider>
        </body>
    </html>
  )
}
